#!/bin/bash --login
#
#SBATCH --account=pawsey0106
#SBATCH --time=24:00:00
##SBATCH --time=00:10:00
#SBATCH --partition=workq
##SBATCH --partition=debugq
#SBATCH --output=LOGS/kdvshifter-%j.out
#SBATCH --nodes=6
#SBATCH --ntasks=144
##SBATCH --nodes=1
##SBATCH --ntasks=24
#SBATCH --cpus-per-task=1
##SBATCH --mem=64000
#SBATCH --mail-type=ALL
#SBATCH --mail-user=matt.rayson@uwa.edu.au

module load shifter

export SOLITON_HOME=$MYSCRATCH/KDV
export CODE_DIR=$MYGROUP/KDV

srun -u --export=all \
    shifter run --mpi mrayson/iwaves \
    python -u scripts/run_pde_solver_mpi.py \
        --beta_infile $CODE_DIR/inputs/ShellCrux_Uniltered_Density_BHM_VI_20162017.h5 \
        --a0_infile $CODE_DIR/inputs/a0_samples_harmonic_a0_all_times.h5 \
        --output_x 100000 \
        --num_samples 500 \
        --tp_min 1\
        --tp_max 374
