#!/bin/bash --login
#
#SBATCH --account=pawsey0106
#SBATCH --time=08:00:00
##SBATCH --time=00:10:00
#SBATCH --partition=workq
##SBATCH --partition=debugq
#SBATCH --output=LOGS/vkdvsingularity-%j.out
#SBATCH --nodes=8
#SBATCH --ntasks=192
##SBATCH --nodes=1
##SBATCH --ntasks=24
#SBATCH --cpus-per-task=1
##SBATCH --mem=64000
#SBATCH --mail-type=ALL
#SBATCH --mail-user=matt.rayson@uwa.edu.au

module load singularity
  
# Define the container to use
#export myRepository=$MYGROUP/singularity/ocean-python
#export containerImage=$myRepository/ocean-python_sfoda001_iwaves040.sif
#PYTHONSCRIPT=scripts/run_vkdv_solver_mpi.py 

#export containerImage=$myRepository/ocean_python_sfoda005_iwaves050.sif
#export containerImage=docker://mrayson/ocean_python:sfoda005_iwaves050
export containerImage=ocean_python_sfoda005_iwaves050.sif
PYTHONSCRIPT=scripts/run_vkdv_arn_solver_mpi.py 

export SOLITON_HOME=$MYSCRATCH/KDV
export CODE_DIR=$MYGROUP/KDV

srun -u --export=all \
    -n $SLURM_NTASKS singularity exec $containerImage \
    python -u $PYTHONSCRIPT\
        --beta_infile $CODE_DIR/inputs/$3 \
        --a0_infile $CODE_DIR/inputs/$1 \
        --infile ./data/kdvin.yml \
        --depthfile ./data/kdv_bathy_Prelude_WELGA_bathy.csv \
        --num_samples $5 \
        --outpath $2 \
        --num_tp $4

